---
driver:
  name: vagrant

provisioner:
  name: chef_zero

require_chef_omnibus: 12.4.2

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[docker-base::default]
    attributes:
